=begin
Sample API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'GET', '/items', controller_name: 'default', action_name: 'items_get'
  add_openapi_route 'DELETE', '/items/{id}', controller_name: 'default', action_name: 'items_id_delete'
  add_openapi_route 'GET', '/items/{id}', controller_name: 'default', action_name: 'items_id_get'
  add_openapi_route 'PATCH', '/items/{id}', controller_name: 'default', action_name: 'items_id_patch'
  add_openapi_route 'PUT', '/items/{id}', controller_name: 'default', action_name: 'items_id_put'
  add_openapi_route 'POST', '/items', controller_name: 'default', action_name: 'items_post'
end
