=begin
Sample API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def items_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def items_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def items_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def items_id_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def items_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def items_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
